---
title: "oREV-VN"
output: html_document
date: "2026-02-25"
---


```{r setup, include=FALSE}
library(papaja)
library(tidyverse)
library(brms)
library(ggthemes)
library(ggridges)
library(geomtextpath)
library(ggrepel)
library(tidybayes)
library(coda)
library(mirt)
library(readxl)
library(ggpubr)
library(testing)
require(cowplot)
library(grid)
```


```{r}
estimate_mode <- function(s) {
  d <- density(s)
  return(d$x[which.max(d$y)])
}

hdi_upper<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","upper"])
}

hdi_lower<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","lower"])
}

func <- function(x){
  abs(1-x)
}
```

# Data

```{r}
data <-read_csv("../data/data.csv")
```
# Age and condition effects

```{r}
mdata <- data%>%
  mutate(z.age = scale(age),
         correct = as.numeric(correct))


bm1 <- brm(correct ~ z.age * word_class + (word_class|id),
    data = mdata,
    chains = 4,
    cores = 4,
    iter = 4000,
    family = bernoulli(),
    threads = threading(2),
    control = list(adapt_delta = 0.95, max_treedepth = 20)
    )

brms::fixef(bm1)%>%as_tibble(rownames = "par")%>%saveRDS("../saves/descrivitve_results.rds")
```

```{r}
ndata <- mdata%>%
  select(word_class, z.age, age)


post <- fitted(bm1, newdata = ndata, re_formula =NA)%>%
  bind_cols(ndata)

saveRDS(post, "../saves/post.rds")
```


# IRT Models

## 1PL Model

```{r}
prior_1pl <- 
  prior("normal(0, 2)", class = "b", nlpar = "eta") +
  prior("normal(0, 1)", class = "sd", group = "id", nlpar = "eta") + 
  prior("normal(0, 3)", class = "sd", group = "target_word", nlpar = "eta")
```

```{r}
irt1_v <- brm(
  data = data%>%filter(word_class == "verb"),
  family = brmsfamily("bernoulli", "identity"),
  bf(
    correct ~ 0.25 + 0.75 * inv_logit(eta),
    eta ~ 1 + (1 | target_word) + (1 | id),
    nl = TRUE
  ),
  prior = prior_1pl,
  control = list(adapt_delta = 0.95, max_treedepth = 12),
  cores = 4,
  chains = 4,
  threads = threading(8), backend = "cmdstanr",
  iter = 4000
)%>%add_criterion(c("loo","waic")) 


saveRDS(irt1_v, "../saves/irt1_v.rds")

irt1_v <- readRDS("../saves/irt1_v.rds")
```

```{r}
icc1_v <- posterior_samples(irt1_v)%>% 
  select(b_eta_Intercept, starts_with("r_target_word"))%>%
  mutate(iter = 1:n()) %>% 
  pivot_longer(starts_with("r_target_word"), names_to = "item", values_to = "xi") %>%
  mutate(item = str_extract(string = item, pattern = "(?<=\\[).*(?=,Intercept\\])"))%>%
  expand(nesting(iter, b_eta_Intercept, item, xi),
         theta = seq(from = -6, to = 6, length.out = 100)) %>% 
  mutate(p = 0.25 + 0.75*inv_logit_scaled((b_eta_Intercept + theta + xi))) %>%  
  group_by(theta, item) %>% 
  summarise(p = mean(p))%>%
  left_join(data%>%filter(word_class == "verb")%>%rename(item = target_word)%>%select(item, word_class)%>%distinct(item, .keep_all = T))

saveRDS(icc1_v, "../saves/icc1_v.rds")

icc1_v <- readRDS("../saves/icc1_v.rds")
```

```{r}
icc1_v %>% 
  #filter(item %in% sel_items_rasch)%>%
  ggplot(aes(x = theta, y = p,group = item), col = item) +
  geom_line() +
  #facet_wrap(~word_class)+
  #guides(col = F)+
  geom_hline(yintercept = 0.25, lty = 3, alpha = .75)+
  #scale_color_ptol(name = "Word class") +
  labs(title = "ICCs for the 1PL",
       x = expression(theta~('ability on the logit scale')),
       y = expression(italic(p)(y==1))) +
  ylim(0,1)+
  theme_bw()
```

```{r}
coef_irt1_v <- coef(irt1_v)$target_word[, , "eta_Intercept"] %>%
	as_tibble(rownames = "item")%>%
  left_join(data%>%filter(word_class == "verb")%>%rename(item = target_word)%>%select(item, word_class)%>%distinct(item, .keep_all = T))

ggplot(coef_irt1_v%>%filter(word_class == "verb"),aes(y = reorder(item, Estimate), x = Estimate, xmin = Q2.5, xmax = Q97.5)) +
	#facet_grid(word_class~., scales = "free") +
	geom_pointrange() +
	#coord_flip() +
  xlab("Easiness")+
  ylab("Item (verb)")+
  scale_color_ptol(name = "")+
  theme_calc()

saveRDS(coef_irt1_v, "../saves/coef_irt1_v.rds")

coef_irt1_v <- readRDS("../saves/coef_irt1_v.rds")


```

```{r}
rasch_draws_fit_v <- data%>%filter(word_class == "verb")%>%
  ungroup()%>%
  add_epred_draws(irt1_v, re_formula = ~(1 | target_word) + (1 | id), ndraws = 1000)

rasch_fit_fit_v <- rasch_draws_fit_v%>%
  mutate(correct = as.numeric(correct))%>%
  mutate(zvi = (correct - .epred)/(.epred*(1-.epred))^0.5)%>%
  group_by(target_word, .draw)%>%
  summarise(outfit = sum(zvi^2)/length(unique(id)),
            infit = (sum(zvi^2*(.epred*(1-.epred)))/sum(.epred*(1-.epred))))

rasch_fit_mode_fit_v <- rasch_fit_fit_v%>%
  pivot_longer(names_to = "fit_index", values_to = "value", cols = c(outfit, infit))%>%
  group_by(target_word, fit_index)%>%
  summarise(mode = estimate_mode(value),
            lci = hdi_lower(value),
            uci = hdi_upper(value))

saveRDS(rasch_fit_mode_fit_v, "../saves/rasch_fit_mode_fit_v.rds")

rasch_fit_mode_fit_v <- readRDS("../saves/rasch_fit_mode_fit_v.rds")
```

```{r}
rasch_fit_mode_fit_v%>%
  ggplot(aes(x = mode, y = target_word, col = fit_index))+
  geom_pointrange(aes(xmin = lci, xmax = uci), position = position_dodge(width = 0.5))+
  scale_color_colorblind()+
  theme_minimal()
```


## 2PL Model
```{r}
prior_2pl <- 
  prior("normal(0, 2)", class = "b", nlpar = "eta") +
  prior("normal(0, 1)", class = "b", nlpar = "logalpha") +
  prior("normal(0, 1)", class = "sd", group = "id", nlpar = "eta") + 
  prior("normal(0, 3)", class = "sd", group = "target_word", nlpar = "eta") +
  prior("normal(0, 1)", class = "sd", group = "target_word", nlpar = "logalpha")
```

```{r}
## 2PL Model
irt2_v <- brm(
  data = data%>%filter(word_class == "verb"),
  family = brmsfamily("bernoulli", "identity"),
  bf(
    correct ~ 0.25 + 0.75 * inv_logit(exp(logalpha) * eta),
    eta ~ 1 + (1 |i| target_word) + (1 | id),
    logalpha ~ 1 + (1 |i| target_word),
    nl = TRUE
  ),
  prior = prior_2pl,
  control = list(adapt_delta = 0.95, max_treedepth = 12),
  cores = 4,
  chains = 4,
  threads = threading(8), backend = "cmdstanr",
  iter = 4000
)%>%add_criterion(c("loo","waic")) 

saveRDS(irt2_v, "../saves/irt2_v.rds")

irt2_v <- readRDS("../saves/irt2_v.rds")
```

```{r}
icc2_v <- posterior_samples(irt2_v)%>% 
  select(b_eta_Intercept, b_logalpha_Intercept, starts_with("r_target_word"))%>%
  mutate(iter = 1:n()) %>% 
  pivot_longer(starts_with("r_target_word")) %>%
  mutate(item      = str_extract(name, pattern = "(?<=\\[).*(?=,Intercept\\])"),
         parameter = ifelse(str_detect(name, "eta"), "xi", "logalpha"))%>%
  select(-name) %>% 
  pivot_wider(names_from = parameter, values_from = value)%>% 
  expand(nesting(iter, b_eta_Intercept, b_logalpha_Intercept, item, xi, logalpha),
         theta = seq(from = -6, to = 6, length.out = 100)) %>% 
  mutate(p = 0.25 + 0.75*inv_logit_scaled(exp(b_logalpha_Intercept + logalpha) * (b_eta_Intercept + theta + xi))) %>% 
  group_by(theta, item) %>% 
  summarise(p = mean(p))%>%
  left_join(data%>%filter(word_class == "verb")%>%rename(item = target_word)%>%select(item, word_class)%>%distinct(item, .keep_all = T))

saveRDS(icc2_v, "../saves/icc2_v.rds")

icc2_v <- readRDS("../saves/icc2_v.rds")

```

```{r}
icc2_v %>% 
  ggplot(aes(x = theta, y = p,group = item)) +
  geom_line() +
  #eom_text_repel(data = icc2%>%group_by(word_class,item)%>%summarise(p = mean(p))%>%mutate(theta = 0), aes(label = item)) +
  #geom_textpath(aes(label = item)) +
  geom_hline(yintercept = 0.25, lty = 3, alpha = .75)+
  #facet_wrap(~word_class)+
  #facet_wrap(~item)+
  guides(col = F)+
  #scale_color_ptol(name = "Word class") +
  labs(title = "ICCs for the 2PL",
       x = expression(theta~('ability on the logit scale')),
       y = expression(italic(p)(y==1))) +
  ylim(0,1)+
  theme_bw()
```

```{r}
ggsave("../visuals/icc_2pl_v.pdf", width = 12, height = 4, scale = 1.5)
```

```{r}
coef_irt2_v <- coef(irt2_v)

eta_v <- coef_irt2_v$target_word[, , "eta_Intercept"] %>%
	as_tibble(rownames = "item")

alpha_v <- coef_irt2_v$target_word[, , "logalpha_Intercept"] %>%
	exp() %>%
	as_tibble(rownames = "item")

params2PL_v <- bind_rows(eta_v, alpha_v, .id = "nlpar") %>%
	select(-Est.Error) %>%
	mutate(nlpar = factor(nlpar, labels = c("Easiness", "Discrimination")))%>%
  left_join(data%>%filter(word_class == "verb")%>%rename(item = target_word)%>%select(item, word_class)%>%distinct(item, .keep_all = T))

saveRDS(params2PL_v, "../saves/params2PL_v.rds")

params2PL_v <- readRDS("../saves/params2PL_v.rds")

ggplot(params2PL_v,aes(y = reorder(item, Estimate), x = Estimate, xmin = Q2.5, xmax = Q97.5, col = word_class)) +
	facet_grid(word_class~nlpar, scales = "free") +
	geom_pointrange() +
	#coord_flip() +
  scale_color_ptol(name = "")+
  theme_calc()
```

## Model comparisons

```{r}
#loo_compare(irt1, irt2)
loo_compare(irt1_v, irt2_v)

```


```{r}
bind_rows(icc2_v%>%mutate(model = "2PL"), 
          icc1_v%>%mutate(model = "1PL")) %>% 
  #filter(word_class == "verb")%>%
  ggplot(aes(x = theta, y = p, group = interaction(model, item), col = model)) +
  geom_line() +
  #eom_text_repel(data = icc2%>%group_by(word_class,item)%>%summarise(p = mean(p))%>%mutate(theta = 0), aes(label = item)) +
  #geom_textpath(aes(label = item)) +
  geom_hline(yintercept = 0.25, lty = 3, alpha = .75)+
  facet_wrap(~item)+
  #facet_wrap(~item)+
  scale_color_colorblind(name = "Model") +
  labs(#title = "ICCs for the 2PL",
       x = expression(theta~('ability on the logit scale')),
       y = expression(italic(p)(y==1))) +
  theme_bw()
```

```{r}
bind_rows(icc2_v%>%mutate(model = "2PL"), 
          icc1_v%>%mutate(model = "1PL")) %>% 
  filter(word_class == "verb")%>%
  ggplot(aes(x = theta, y = p, group = interaction(model, item), col = model)) +
  geom_line() +
  #eom_text_repel(data = icc2%>%group_by(word_class,item)%>%summarise(p = mean(p))%>%mutate(theta = 0), aes(label = item)) +
  #geom_textpath(aes(label = item)) +
  geom_hline(yintercept = 0.25, lty = 3, alpha = .75)+
  facet_wrap(~item)+
  #facet_wrap(~item)+
  scale_color_colorblind(name = "Model") +
  labs(#title = "ICCs for the 2PL",
       x = expression(theta~('ability on the logit scale')),
       y = expression(italic(p)(y==1))) +
  theme_bw()
```

# Item selection

## Parameters

```{r}
n_nouns <- n_distinct((data%>%filter(word_class == "noun"))$target_word)
n_verbs <- n_distinct((data%>%filter(word_class == "verb"))$target_word)
verbs <- data%>%filter(word_class == "verb")%>%distinct(target_word, .keep_all = T)%>% arrange( target_word)%>%pull(target_word)
easiness_rasch_v <- coef_irt1_v%>%filter(word_class == "verb")%>%arrange(word_class, item)%>%pull(Estimate)
infit_v <- rasch_fit_mode_fit_v%>% arrange(target_word)%>%filter(fit_index == "infit")%>%pull(mode)
outfit_v <- rasch_fit_mode_fit_v%>% arrange(target_word)%>%filter(fit_index == "outfit")%>%pull(mode)
disc_2PL_v <- params2PL_v%>%filter(nlpar == "Discrimination")%>%arrange(item)%>%pull(Estimate)

```

## Simulated annealing algorithm

```{r}
score_fn <- function(subset) {
  
  #subset_c <- c(rep(TRUE, n_nouns), subset)
  subset_c <- subset
	#easinesses <- sort(easiness_rasch[subset_c])
  easinesses <- sort(easiness_rasch_v[subset_c])
	nn_dists <- rep(0, sum(subset_c)-1)
	for(i in 1:sum(subset_c)-1) {
		nn_dists[i] <- easinesses[i+1] - easinesses[i]
	}
	
	range <- -1/sd(easinesses)
	spacing <- -1*sd(nn_dists)/3
	
	var_disc_sample <- disc_2PL_v[subset_c]
	#var_disc_sample <- disc_2PL[subset_c]
	var_disc_2PL <- -1*var(var_disc_sample)*10
	
	infit_sample <- infit_v[subset_c]
	#infit_sample <- infit[subset_c]
	infit_dist <- unlist(lapply(infit_sample, func))
  mean_infit <- -4*mean(infit_dist)
  
	outfit_sample <- outfit_v[subset_c]
	#outfit_sample <- outfit[subset_c]
	outfit_dist <- unlist(lapply(outfit_sample, func))
  mean_outfit <- -2*mean(outfit_dist)
  
	return(spacing + range+ mean_infit + mean_outfit+ var_disc_2PL)
}


proposal_fn <- function(subset) {
	# Randomly sample a number of swaps.
	# Prefer a small number of swaps for "fine tuning", but allow
	# occasional large numbers of swaps, including a complete
	# exchange of the subset
	subset_size = sum(as.integer(subset))
	max_swaps = min(subset_size, length(subset) - subset_size)
	swaps <- rbinom(1, max_swaps-1, 1/(max_swaps-1)) + 1

	# Choose the items to swap
	active_items <- seq(1:length(subset))[subset == TRUE]
	inactive_items <- seq(1:length(subset))[subset == FALSE]
	actives_to_swap <- sample(active_items, swaps)
	inactives_to_swap <- sample(inactive_items, swaps)

	# Do the swapping
	for(i in 1:swaps) {
		subset[actives_to_swap[i]] <- FALSE
		subset[inactives_to_swap[i]] <- TRUE
	}
	return(subset)
}

simulated_annealing_rasch <- function(k, cooling_ratio=0.999, reset_thresh=1000, break_thresh=10000) {
  
verbs <- data%>%filter(word_class == "verb")%>%distinct(target_word, .keep_all = T)%>% arrange( target_word)%>%pull(target_word)
easiness_rasch_v <- coef_irt1_v%>%filter(word_class == "verb")%>%arrange(word_class, item)%>%pull(Estimate)
infit_v <- rasch_fit_mode_fit_v%>% arrange(target_word)%>%filter(fit_index == "infit")%>%pull(mode)
outfit_v <- rasch_fit_mode_fit_v%>% arrange(target_word)%>%filter(fit_index == "outfit")%>%pull(mode)
disc_2PL_v <- params2PL_v%>%filter(nlpar == "Discrimination")%>%arrange(item)%>%pull(Estimate)

  N <- n_verbs

	current_subset <- sample(c(rep(TRUE, k), rep(FALSE, N-k)))
	best_subset <- current_subset
	best_score <- score_fn(best_subset)

	temp <- 100
	rejected <- 0
	no_new_bests <- 0
	for(i in 1:1e6) {
		# Score new subset, and toss a coin
		new_subset <- proposal_fn(current_subset)
		new_score <- score_fn(new_subset)
		accept_decrease <- rbernoulli(1, temp / 100)

		# Accept the new subset if it's an improvement, or if our
		# cooling coin came up heads.
		if(new_score > best_score | accept_decrease) {
			current_subset <- new_subset
			rejected <- 0
			if(new_score > best_score) {
				best_subset <- new_subset
				best_score <- new_score
				no_new_bests <- 0
			} else {
				no_new_bests <- no_new_bests + 1
			}
		# Quit if we've had too many rejections in a row.
		} else {
			rejected <- rejected + 1
			no_new_bests <- no_new_bests + 1
			if(rejected == break_thresh) {
				#print(best_score)
			  ret <- tibble(best_subset = list(best_subset),
	              best_score = best_score)
			  
				return(ret)
			}
		}
		# Start random resets to the current best subset if we haven't
		# found anything better in quite a while.
		if(no_new_bests > reset_thresh & rbernoulli(1, 1/100)) {
			current_subset <- best_subset
		}

		# Cool it!
		temp <- temp*cooling_ratio
	}
	#print(best_score)
	ret <- tibble(best_subset = list(best_subset),
	              best_score = best_score)
	
	return(ret)
}
```

```{r}
# test run
#sim <- simulated_annealing_rasch(10)
```

## Determine size

```{r}
# determine_size_v <- tibble()
# 
#   for(j in 1:5){
# 
#   for (i in c(5:18)) {
# 
#     sim <- simulated_annealing_rasch(i)
# 
#     sel <- verbs[unlist(sim$best_subset) == TRUE]
# 
#     sub_dat <- data%>%filter(target_word %in% sel)
# 
#     m1PL <- update(irt1_v, newdata =sub_dat, chains = 4, cores = 4, threads = threading(8), backend = "cmdstanr")%>%add_criterion(c("loo"))
#   	m2PL <- update(irt2_v, newdata =sub_dat, chains = 4, cores = 4, threads = threading(8), backend = "cmdstanr")%>%add_criterion(c("loo"))
# 
#   	comp <- loo_compare(m1PL, m2PL)%>%as_tibble(rownames = "model")%>%mutate(items = list(sel), size = i, iter = j)%>%mutate_at(c(2:9), as.numeric)
# 
#     determine_size_v <- bind_rows(determine_size_v, comp)
# 
#     saveRDS(determine_size_v, "../saves/determine_size_v.rds")
#   }
# 
#   }
# 
# saveRDS(determine_size_v, "../saves/determine_size_v.rds")

determine_size_v <- readRDS("../saves/determine_size_v.rds")
```

## Selected items

```{r}
sel_verbs <- tibble()

for(j in 1:1){

  #for (i in c(5:18)) {

    sim <- simulated_annealing_rasch(11)

    #sel <- items[c(rep(TRUE, 22), unlist(sim$best_subset) == TRUE)]
    sel <-verbs[unlist(sim$best_subset) == TRUE]

    row <- tibble(#size = i,
           iter = j,
           items = sel)

    sel_verbs <- bind_rows(sel_verbs, row)
   # }

}
```

```{r}
sel_verbs%>%
  right_join(data%>%dplyr::rename(items = target_word)%>%distinct(items, word_class))%>%
  filter(word_class == "verb")%>%
  group_by(items)%>%
  summarise(sum = n())%>%
  ggplot(aes(x = reorder(items, -sum), y = sum/5))+
  geom_bar(stat = "identity")+
  labs(x = "Verb", y = "Proportion selected")+
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```


```{r}
verbs_selected <- sel_verbs%>%
  group_by(items)%>%
  summarise(n = n())%>%
  head(11)%>%
  pull(items)

saveRDS(verbs_selected, "../saves/selected_verbs.rds")

verbs_selected <- readRDS("../saves/selected_verbs.rds")
```


# Selected items

## Fit indices
```{r}
frq_dat <- data%>%
  filter(target_word %in% verbs_selected)%>%
  distinct(id, target_word, .keep_all = T)%>%
  select(id, target_word, correct)%>%
  mutate(correct = as.numeric(correct))%>%
  pivot_wider(names_from = target_word, values_from = correct)%>%
  select( -id)%>%
  na.omit()


freq_mirt <- mirt(frq_dat, 1, itemtype='Rasch', verbose=TRUE, guess = 0.25,na.rm=TRUE, technical = list(NCYCLES = 5000))

M2(freq_mirt)
```

## ICC

```{r}
icc1_v %>% 
  filter(item %in% verbs_selected)%>%
  ggplot(aes(x = theta, y = p,group = item), col = item) +
  geom_line() +
  #facet_wrap(~word_class)+
  #guides(col = F)+
  geom_hline(yintercept = 0.25, lty = 3, alpha = .75)+
  #scale_color_ptol(name = "Word class") +
  labs(title = "ICCs for the 1PL",
       x = expression(theta~('ability on the logit scale')),
       y = expression(italic(p)(y==1))) +
  ylim(0,1)+
  theme_bw()
```

```{r}
verbstab <- read_xlsx("../data/verbs_overview.xlsx")%>%
  mutate(`Target word` = paste0(target_de, " ", "(to ",EN_translation...2,")"),
         `Semantic` = paste0(SEMANTIC_de, " ", "(to ",EN_translation...4,")"),
         `Phonological` = paste0(PHONOLOGICAL_de, " ", "(to ",EN_translation...8,")"),
         `Unrelated` = paste0(UNRELATED_de, " ", "(to ",EN_translation...6,")"))%>%
  mutate(`Selected` = ifelse(target_de %in% readRDS("../saves/selected_verbs.rds"), "yes", "no"))%>%
  select(`Target word`, Semantic, Phonological, Unrelated, Selected)%>%
  write_rds("../saves/verbs.rds")
```


## DIF

```{r}
irt1_dif <- brm(
  data = data%>%filter(target_word %in% verbs_selected),
  family = brmsfamily("bernoulli", "identity"),
  bf(
    correct ~ 0.25 + 0.75 * inv_logit(eta),
    eta ~ source + (0 + source | target_word) + (1 | id),
    nl = TRUE
  ),
  prior = prior_1pl,
  control = list(adapt_delta = 0.95, max_treedepth = 12),
  cores = 4,
  threads = threading(2), #backend = "cmdstanr",
  chains = 4,
  iter = 6000
)%>%add_criterion(c("loo","waic")) 


saveRDS(irt1_dif, "../saves/irt1_dif.rds")

irt1_dif <- readRDS("../saves/irt1_dif.rds")
```

```{r}
dif_source <- as_draws_df(irt1_dif)%>%
  select(b_eta_Intercept, starts_with("r_target_word"))%>%
  mutate(iter = 1:n()) %>%
  pivot_longer(starts_with("r_target_word")) %>%
  mutate(name = str_remove(name, pattern = "r_target_word__eta"),
         name = str_remove_all(name, pattern = "\\[|\\]"))%>%
  separate(name, into = c("item", "source"), sep = "\\,")%>%
  mutate(source = str_remove(source, pattern = "source"),
         val =  value)%>%
  group_by(item, source)%>%
  summarise(mode = estimate_mode(val),
            uci = hdi_upper(val),
            lci = hdi_lower(val))

saveRDS(dif_source, "../saves/dif_source.rds")

dif_source <- readRDS("../saves/dif_source.rds")

dif_source%>%
  group_by(item)%>%
  mutate(dif = abs(abs(mode) - lag(abs(mode))))%>%
  fill(dif, .direction = "up")%>%
ggplot(.,aes(x = reorder(item, dif))) +
	geom_point(aes(col = source, y = lci), position = position_dodge(width = .5)) +
  geom_point(aes(col = source, y = uci), position = position_dodge(width = .5)) +
  geom_linerange(aes(col = source, ymin = lci + 0.1, ymax = uci-0.1), position = position_dodge(width = .5), alpha = .5) +
	coord_flip() +
  scale_color_colorblind(labels = c("lg","lpz"), name = "Group")+
	labs(x = "Item", y = "Easiness estimate")+
  theme_minimal()
```

```{r}
dif_source%>%
  pivot_wider(names_from = source, values_from = c(mode,uci,lci))%>%
  ggplot(., aes(x = mode_lpz, y = mode_lg))+
  geom_abline(intercept = 0, slope = 1, lty = 3, alpha = .75)+
  geom_point(pch = 1, size = 2, stroke  = 1)+
  geom_linerange(aes(ymin = lci_lg, ymax = uci_lg),  alpha = .25, lty = 1)+
  geom_linerange(aes(xmin = lci_lpz, xmax = uci_lpz),  alpha = .25, lty = 1)+
  stat_cor(aes(x = mode_lpz, y = mode_lg,label = paste(..r.label..)),inherit.aes = F,r.accuracy = 0.01, cor.coef.name = "r")+
  #geom_text(aes(label = item, x = uci_f +0.2))+
  labs(x = "Group: lg", y = "Group: lpz")+
  scale_color_viridis_d()+
  guides(col = F)+
  coord_fixed()+
  theme_few()
  
```


# Combined model verbs and nouns

```{r}
selection <- c(unique(data$target_word[data$word_class == "noun"]), verbs_selected)
```

## Combined model

```{r}
irt1_c <- brm(
  data = data%>%filter(target_word %in% selection),
  family = brmsfamily("bernoulli", "identity"),
  bf(
    correct ~ 0.25 + 0.75 * inv_logit(eta),
    eta ~ 1 + (1 | target_word) + (1 | id),
    nl = TRUE
  ),
  prior = prior_1pl,
  control = list(adapt_delta = 0.95, max_treedepth = 12),
  cores = 4,
  threads = threading(2), #backend = "cmdstanr",
  chains = 4,
  iter = 8000
)%>%add_criterion(c("loo","waic")) 


saveRDS(irt1_c, "../saves/irt1_c.rds")

irt1_c <- readRDS("../saves/irt1_c.rds")
```

## Fit indices

```{r}
frq_dat_c <- data%>%
  filter(target_word %in% selection)%>%
  distinct(id, target_word, .keep_all = T)%>%
  select(id, target_word, correct)%>%
  mutate(correct = as.numeric(correct))%>%
  pivot_wider(names_from = target_word, values_from = correct)%>%
  select( -id)%>%
  na.omit()


freq_mirt_c <- mirt(frq_dat_c, 1, itemtype='Rasch', verbose=TRUE, guess = 0.25,na.rm=TRUE, technical = list(NCYCLES = 5000))

M2(freq_mirt_c)
```
## Combined model

```{r}
irt1_c <- brm(
  data = data%>%filter(target_word %in% selection),
  family = brmsfamily("bernoulli", "identity"),
  bf(
    correct ~ 0.25 + 0.75 * inv_logit(eta),
    eta ~ 1 + (1 | target_word) + (1 | id),
    nl = TRUE
  ),
  prior = prior_1pl,
  control = list(adapt_delta = 0.95, max_treedepth = 12),
  cores = 4,
  threads = threading(2), #backend = "cmdstanr",
  chains = 4,
  iter = 8000
)%>%add_criterion(c("loo","waic")) 


saveRDS(irt1_c, "../saves/irt1_c.rds")

irt1_c <- readRDS("../saves/irt1_c.rds")
```

## ICC

```{r}
icc1_c <- posterior_samples(irt1_c)%>% 
  select(b_eta_Intercept, starts_with("r_target_word"))%>%
  mutate(iter = 1:n()) %>% 
  pivot_longer(starts_with("r_target_word"), names_to = "item", values_to = "xi") %>%
  mutate(item = str_extract(string = item, pattern = "(?<=\\[).*(?=,Intercept\\])"))%>%
  expand(nesting(iter, b_eta_Intercept, item, xi),
         theta = seq(from = -6, to = 6, length.out = 100)) %>% 
  mutate(p = 0.25 + 0.75*inv_logit_scaled((b_eta_Intercept + theta + xi))) %>%  
  group_by(theta, item) %>% 
  summarise(p = mean(p))%>%
  left_join(data%>%rename(item = target_word)%>%select(item, word_class)%>%distinct(item, .keep_all = T))

saveRDS(icc1_c, "../saves/icc1_c.rds")

icc1_c <- readRDS("../saves/icc1_c.rds")
```

```{r}
icc1_c %>% 
  ggplot(aes(x = theta, y = p,group = item, col = word_class)) +
  geom_line() +
  #facet_wrap(~word_class)+
  #guides(col = F)+
  geom_hline(yintercept = 0.25, lty = 3, alpha = .75)+
  scale_color_manual(name = "Word class", values = c("lightgrey", "#CC6677")) +
  labs(title = "ICCs for the 1PL",
       x = expression(theta~('ability on the logit scale')),
       y = expression(italic(p)(y==1))) +
  ylim(0,1)+
  theme_few()+
  theme(legend.position = c(0.9, 0.5))
```

## Reliability

```{r}
frq_dat_v <- data%>%
  filter(target_word %in% verbs_selected)%>%
  distinct(id, target_word, .keep_all = T)%>%
  select(id, target_word, correct)%>%
  mutate(correct = as.numeric(correct))%>%
  pivot_wider(names_from = target_word, values_from = correct)%>%
  select( -id)%>%
  na.omit()
```


### KR20

```{r}
kr20_v <- kr20(frq_dat_v, hit = 1)

kr20_v%>%saveRDS("../saves/rel_v.rds")

kr20_c <- kr20(frq_dat_c, hit = 1)

kr20_c%>%saveRDS("../saves/rel_c.rds")
```

### Andrich Reliability

```{r}
pers_params <- ranef(irt1_c)$id%>%as_tibble(rownames = "id")

andrich_rel <- 1 -
  (1/length(pers_params$Estimate.eta_Intercept) * sum(pers_params$Est.Error.eta_Intercept^2))/
  (1/(length(pers_params$Estimate.eta_Intercept)-1)*sum((pers_params$Estimate.eta_Intercept - mean(pers_params$Estimate.eta_Intercept))^2))

andrich_rel
```

```{r}
tibble(type = c("kr20", "andrich"),
       rel = c(kr20_rel, andrich_rel))%>%
  saveRDS("../saves/reliability.rds")
```

## Validity

```{r}
cord <- data%>%
  filter(target_word %in% selection)%>%
  group_by(word_class, id, age)%>%
  summarise(perf = mean(correct))%>%
  mutate(age_group = substr(age,1,1))%>%
  pivot_wider(names_from = word_class, values_from = perf)%>%
  ungroup()

val <- cor.test(cord$noun, cord$verb)

saveRDS(val, "../saves/val.rds")
```


# Visuals

```{r}
pac <- data%>%
  group_by(word_class, id, age)%>%
  summarise(perf = mean(correct))%>%
  ggplot(aes(x = age, y = perf, col = word_class, fill = word_class))+
  geom_hline(yintercept = 0.25, lty = 3, alpha = 0.5)+
  geom_point(pch = 1, alpha = 0.5)+
  #geom_smooth(method = "loess", alpha = .2)+
  geom_smooth(data = post, aes(x = age, y = Estimate, ymin = Q2.5, ymax = Q97.5, fill =word_class, col = word_class), stat = "identity", alpha = .25)+
  lims(y = c(0,1)) +
  labs(x = "Age in years", y = "Proportion correct")+
  scale_x_continuous(breaks = c(3, 4, 5, 6, 7, 8))+
  scale_color_colorblind(name = "")+
  scale_fill_colorblind(name = "")+
  #facet_grid(~word_type)+
  theme_few()+
  theme(legend.position = c(0.85, 0.15))
  

pcor <- data%>%
  #filter(target_word %in% selection)%>%
  group_by(word_class, id, age)%>%
  summarise(perf = mean(correct))%>%
  pivot_wider(names_from = word_class, values_from = perf)%>%
  ggplot(aes(x = verb, y = noun, col = age))+
  geom_hline(yintercept = 0.25, lty = 3, alpha = 0.5)+
  geom_vline(xintercept = 0.25, lty = 3, alpha = 0.5)+
  geom_jitter(pch = 1, alpha = 0.5, height = 0.01, width = 0.01)+
  geom_smooth(method = "lm", alpha = .2, col = "black")+
  lims(x = c(0,1), y = c(0,1))+
  stat_cor(aes(x = verb, y = noun,label = paste(..r.label..)),inherit.aes = F,r.accuracy = 0.01, cor.coef.name = "r")+
  labs(x = "Verbs (prop. correct)", y = "Nouns (prop. correct)")+
  scale_color_viridis_c(name = "Child age")+
  #facet_grid(~word_type)+
  theme_few()+
  theme(legend.position = c(0.7, 0.15), legend.direction = "horizontal", legend.title.position = "top")

```

```{r}
# img <- image_read("../visuals/task.pdf", density = 300)
# img <- image_convert(img, format = "png")  # convert to raster-friendly format
# img_grob <- rasterGrob(as.raster(img), interpolate = TRUE)
# img_plot <- ggdraw() +
#   draw_grob(img_grob)

```

```{r}
plot_grid(pac, pcor, rel_widths = c(1.5,1), labels = c("A", "B"), align = "h")
```

```{r}
ggsave("../visuals/fig2.pdf", width = 10, height = 4, scale = 1)
```


```{r}
psize <- readRDS("../saves/determine_size_v.rds")%>%
  mutate(ratio = abs(elpd_diff) / (2*se_diff))%>%
  mutate(ratio = ifelse( elpd_diff == 0,0,ratio))%>%
  filter(ratio != 0)%>%
  mutate(ratio = ifelse(model == "m2PL", ratio*-1, ratio))%>%
  arrange(iter, size)%>%
  #pivot_longer(cols = c(ratio, correlation), names_to = "type",values_to = "value")%>%
  ggplot(aes(y = factor(size), x = ratio, group = factor(iter)))+
  geom_vline(xintercept = c(-1,1), alpha = 1, lty = 3)+
  geom_vline(xintercept = 0, col = "black", lty = 1, size = 1)+
  geom_point(alpha = .5, size = 3)+
  #geom_line(aes(group = size), alpha = .25)+
  #geom_path(aes(group = iter), alpha = .25)+
  scale_y_discrete(breaks = c(5:18))+
  scale_x_continuous( limits = c(-3,3), breaks = c(-2, -1, 0, 1, 2), labels = c("2.00","1.00","0.00", "1.00","2.00"))+
  scale_color_ptol(guide = "none")+
  #geom_line()+
  #facet_grid(type~. , scales = "free_y")+
  theme_bw()+
  theme(panel.grid.minor = element_blank())+
  labs(y = "No. of items in subset", x = expression(paste("Model comparison: ", frac(Delta ~ elpd, "2 *"~SE(Delta ~ elpd)))))+
  annotation_custom(textGrob("1PL wins", 
                             gp=gpar(fontsize=13,
                                     col = "black", 
                                     fontface="bold")),
                    xmin=-2, xmax=-2, ymin="10", ymax="10") +
  annotation_custom(textGrob("2PL wins",
                             gp=gpar(fontsize=13,
                                     col = "black",
                                     fontface="bold")),
                    xmin=2, xmax=2, ymin="10", ymax="10")#+
  theme(
        panel.grid.major.y = element_line(size = 0.1))


p_icc <- icc1_c %>% 
  ggplot(aes(x = theta, y = p,group = item, col = word_class)) +
  geom_line() +
  #facet_wrap(~word_class)+
  #guides(col = F)+
  geom_hline(yintercept = 0.25, lty = 3, alpha = .75)+
  scale_color_manual(name = "Word class", values = c("lightgrey", "#CC6677")) +
  labs(#title = "ICCs for the 1PL",
       x = expression(theta~('ability on the logit scale')),
       y = expression(italic(p)(y==1))) +
  ylim(0,1)+
  theme_few()+
  theme(legend.position = c(0.9, 0.5))
```

```{r}
plot_grid(psize, p_icc, rel_widths = c(1,1.5), labels = c("A", "B"), align = "h")
```

```{r}
ggsave("../visuals/fig3.pdf", width = 10, height = 4, scale = 1)
```